apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec: # pod config
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template: # docker image config
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef: 
              name: mongodb-secret
              key: mongo_root_username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mongodb-secret
              key: mongo_root_password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service # this can be anything
spec:
  selector:
    app: mongodb # this service is connected to pods with the same label
  ports:
    - protocol: TCP
      port: 27017 # incoming port
      targetPort: 27017 # internal port

